import type { LeadershipContent } from "@/lib/translations";

export const leadershipEn: LeadershipContent = {
	title: "Meet our leadership team",
	items: [
		{
			id: "chef-group",
			name: "Ghinwa Ounaissy",
			role: "Chef de groupe",
			bio: "Guides the entire troop, mentors leaders, and ensures every program stays true to our mission.",
			photo: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "assistant-chef",
			name: "Nicolas Nasr",
			role: "Assistant chef de groupe",
			bio: "Supports logistics and high-adventure programming, bringing engineering precision to every camp.",
			photo: "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "secretary",
			name: "Petina Abi Hanna",
			role: "Secretary (Amin Serr)",
			bio: "Keeps parent communication flowing and archives the troop’s memories and milestones.",
			photo: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "treasurer",
			name: "Francois Abi Char",
			role: "Treasurer (Amin Sandouq)",
			bio: "Oversees budgets and fundraising so every scout can participate fully.",
			photo: "https://images.unsplash.com/photo-1502767089025-6572583495b4?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "quartermaster",
			name: "Rayen Merhi",
			role: "Quartermaster (Amin Tajhizet)",
			bio: "Maintains gear, transportation, and safety kits for every outing.",
			photo: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "operations-lead",
			name: "Pinella Abi Hanna",
			role: "Administrative lead",
			bio: "Coordinates calendars, permissions, and training so volunteers stay aligned.",
			photo: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "operations-lead-2",
			name: "Charly Nasr",
			role: "Administrative lead",
			bio: "Coordinates calendars, permissions, and training so volunteers stay aligned.",
			photo: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&q=80",
		},

		{
			id: "operations-lead-3",
			name: "Ibtisam Barakat",
			role: "Administrative lead",
			bio: "Coordinates calendars, permissions, and training so volunteers stay aligned.",
			photo: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "louveteaux-lead",
			name: "Francois",
			role: "Louveteaux unit leader",
			bio: "Builds teamwork through patrol games and first overnight experiences.",
			photo: "https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "louveteaux-assistant",
			name: "Yara Saab",
			role: "Louveteaux assistant",
			bio: "Coaches songs, skits, and service badges for the pack.",
			photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "guides-lead",
			name: "Lea Daher",
			role: "Guides unit leader",
			bio: "Accompanies our Mourchidat through identity-forming outdoor journeys.",
			photo: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "guides-assistant",
			name: "Clara Abboud",
			role: "Guides assistant",
			bio: "Leads prayer circles and reflection moments around the campfire.",
			photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "flowers-lead",
			name: "Michelle",
			role: "Zahrat unit leader",
			bio: "Helps Zaharat discover service through art, dance, and nature walks.",
			photo: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "flowers-assistant",
			name: "Reine",
			role: "Zahrat assistant",
			bio: "Organizes ceremonies and badge tracking for the floral patrols.",
			photo: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "rovers-lead",
			name: "Omar Khoury",
			role: "Jawala unit leader",
			bio: "Mentors Jouwele in leadership rotations and trek planning.",
			photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "rovers-assistant",
			name: "Sami Abou Khalil",
			role: "Jawala assistant",
			bio: "Handles equipment checks and emergency drills for the rovers.",
			photo: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "pioneers-lead",
			name: "Christelle Nassar",
			role: "Mounjidet unit leader",
			bio: "Accompanies senior scouts through discernment, service expeditions, and faith formation.",
			photo: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "pioneers-assistant-1",
			name: "Hiba Gerges",
			role: "Mounjidet assistant",
			bio: "Coordinates formation weekends and service partnerships for the unit.",
			photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80",
		},
		{
			id: "pioneers-assistant-2",
			name: "Ranya Fadel",
			role: "Mounjidet mou3ewen",
			bio: "Supports leadership coaching and accompanies international exchanges.",
			photo: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=600&q=80",
		},
	],
	orgChart: {
		rows: [
			{
				label: "Group leadership",
				highlight: true,
				nodes: [{ leader: "chef-group", assistants: ["assistant-chef"] }],
			},
			{
				label: "Administrative core",
				nodes: [
					{ leader: "secretary", assistants: [""] },
					{ leader: "treasurer", assistants: [""] },
					{ leader: "quartermaster", assistants: [""] },
					{ leader: "operations-lead", assistants: [""] },
					{ leader: "operations-lead-1", assistants: [""] },
					{ leader: "operations-lead-2", assistants: [""] },
					{ leader: "operations-lead-3", assistants: [""] },
				],
			},
			{
				label: "Section leadership",
				nodes: [
					{ leader: "louveteaux-lead", assistants: ["louveteaux-assistant"] },
					{ leader: "flowers-lead", assistants: ["flowers-assistant"] },
					{ leader: "guides-lead", assistants: ["guides-assistant"] },
					{ leader: "rovers-lead", assistants: ["rovers-assistant"] },
					{ leader: "pioneers-lead", assistants: ["pioneers-assistant-1", "pioneers-assistant-2"] },
				],
			},
		],
	},
};
