import type { GalleryPageContent } from "@/lib/translations";

export const galleryPageAr: GalleryPageContent = {
	hero: {
		badge: "المعرض",
		title: "لحظات تصنع مسيرة الكشاف",
		description: "من نار المخيم إلى مشاريع الخدمة، نوثّق قصص الفروع مع العائلات والقادة.",
		image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1600&q=80",
		stats: [
			{ value: "8", label: "ألبومات" },
			{ value: "120+", label: "صورة مختارة" },
			{ value: "6", label: "فروع ممثلة" },
		],
	},
	filters: {
		sectionLabel: "الفروع",
		tagLabel: "الوسوم",
		sortLabel: "الترتيب",
		sortOptions: [
			{ value: "newest", label: "الأحدث أولاً" },
			{ value: "oldest", label: "الأقدم أولاً" },
			{ value: "section", label: "الفروع أبجدياً" },
			{ value: "location", label: "المواقع أبجدياً" },
		],
	},
	albums: [
		{
			id: "family-welcome-2024",
			title: "نار المخيم الترحيبية",
			description: "مساء خريفي تلتقي فيه كل الفروع بالعائلات الجديدة ويُرفع أول نشيد للسنة.",
			coverImage: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
			section: "كل الفروع",
			location: "حديقة سان جان",
			dateRange: "14 أيلول 2024",
			sortDate: "2024-09-14",
			tags: ["نار", "عائلة", "تقاليد"],
			stats: [
				{ value: "18", label: "لقطة" },
				{ value: "6", label: "فروع مشاركة" },
			],
			images: [
				{
					id: "campfire-welcome",
					title: "أول دائرة نار",
					description: "الجرميز يقودون نشيد الترحيب فيما يلتف الأهل حول الجمر.",
					image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
					section: "الجرميز",
					activity: "نار المخيم الترحيبية",
					date: "2024-09-14",
					location: "حديقة سان جان",
					tags: ["نشيد", "انطلاق", "قادة"],
				},
				{
					id: "castors-lanterns",
					title: "موكب الفوانيس",
					description: "القنادس يشاركون الفوانيس التي صنعوها ليرافقوا الإخوة الجدد إلى الدائرة.",
					image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
					section: "القنادس",
					activity: "نار المخيم الترحيبية",
					date: "2024-09-14",
					location: "حديقة سان جان",
					tags: ["حرف", "نور", "فرح"],
				},
				{
					id: "parents-circle",
					title: "جلسة الذكريات",
					description: "الأهل يتبادلون القصص فيما تعرض الطلائع طواطمها الجديدة.",
					image: "https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?auto=format&fit=crop&w=1600&q=80",
					section: "كل الفروع",
					activity: "نار المخيم الترحيبية",
					date: "2024-09-14",
					location: "حديقة سان جان",
					tags: ["أهل", "ذكريات", "طواطم"],
				},
			],
		},
		{
			id: "skills-camp-2024",
			title: "مخيم مهارات الخريف",
			description: "نهاية أسبوع على هضبة الأرز للتركيز على البناء، الطهي، وسهرات الوعد.",
			coverImage: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80",
			section: "الكشافة والرواد",
			location: "هضبة الأرز",
			dateRange: "4 – 6 تشرين الأول 2024",
			sortDate: "2024-10-04",
			tags: ["مخيم", "مهارات", "شارات"],
			stats: [
				{ value: "24", label: "لقطة" },
				{ value: "3", label: "تحديات طلائع" },
			],
			images: [
				{
					id: "skills-camp-flag",
					title: "رفع العلم فجراً",
					description: "الكشافة يثبتون السارية التي بنوها طوال الليل قبل صلاة الصباح.",
					image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80",
					section: "الكشافة",
					activity: "مخيم مهارات الخريف",
					date: "2024-10-05",
					location: "هضبة الأرز",
					tags: ["علم", "فجر", "بناء"],
				},
				{
					id: "pioneers-vigil",
					title: "سهرة الوعد",
					description: "الرواد يسهرون قرب المصلى قبل تجديد الوعد فجراً.",
					image: "https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?auto=format&fit=crop&w=1600&q=80",
					section: "الرواد",
					activity: "مخيم مهارات الخريف",
					date: "2024-10-05",
					location: "هضبة الأرز",
					tags: ["سهرة", "صلاة", "وعد"],
				},
				{
					id: "campfire-chefs",
					title: "مطبخ الطلائع",
					description: "الفرق تتسابق لتحضير أفضل عشاء على الجمر بإشراف الكبار.",
					image: "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1600&q=80",
					section: "الكشافة",
					activity: "مخيم مهارات الخريف",
					date: "2024-10-05",
					location: "هضبة الأرز",
					tags: ["طبخ", "منافسة", "جمر"],
				},
			],
		},
		{
			id: "pilgrimage-2024",
			title: "حج الفصح",
			description: "المرشدات والمنجدات على درب قاديشا مع دفاتر الصلاة والخدمة.",
			coverImage: "https://images.unsplash.com/photo-1521335629791-ce4aec67dd47?auto=format&fit=crop&w=1600&q=80",
			section: "المرشدات والمنجدات",
			location: "درب قاديشا",
			dateRange: "5 – 7 نيسان 2024",
			sortDate: "2024-04-05",
			tags: ["حج", "صلاة", "أخوة"],
			stats: [
				{ value: "12", label: "محطات صلاة" },
				{ value: "9كم", label: "مسار السير" },
			],
			images: [
				{
					id: "guides-pilgrimage",
					title: "استراحة الحج",
					description: "المرشدات يدوّنَّ تأملاتهن فوق الوادي بعد مسار الصوم.",
					image: "https://images.unsplash.com/photo-1521335629791-ce4aec67dd47?auto=format&fit=crop&w=1600&q=80",
					section: "المرشدات",
					activity: "حج الفصح",
					date: "2024-04-07",
					location: "درب قاديشا",
					tags: ["تأمل", "سير", "صلاة"],
				},
				{
					id: "caravelles-sharing",
					title: "رسائل للصديقات",
					description: "المنجدات يكتبن صلوات وتبادلات مع فوج مرسيليا بينما يسترحن عند الإطلالة.",
					image: "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1600&q=80",
					section: "المنجدات",
					activity: "حج الفصح",
					date: "2024-04-06",
					location: "درب قاديشا",
					tags: ["دفتر", "تبادل", "غروب"],
				},
				{
					id: "pilgrimage-altar",
					title: "مذبح الدرب",
					description: "مذبح بسيط من أغصان الأرز للقداس المسائي.",
					image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
					section: "المرشدات",
					activity: "حج الفصح",
					date: "2024-04-06",
					location: "منعطف النسك",
					tags: ["خدمة", "نور", "قداس"],
				},
			],
		},
		{
			id: "service-trail-2024",
			title: "يوم ترميم الدرب",
			description: "الجوالة يرافقون الطلائع الأصغر لإصلاح درج تضرر بالعاصفة.",
			coverImage: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
			section: "الجوالة",
			location: "محمية عين زحلتا",
			dateRange: "18 أيار 2024",
			sortDate: "2024-05-18",
			tags: ["خدمة", "درب", "مرافقة"],
			stats: [
				{ value: "6", label: "طلائع مشاركة" },
				{ value: "180", label: "درجة مرممة" },
			],
			images: [
				{
					id: "routiers-service",
					title: "ترميم الدرج",
					description: "الجوالة يعيدون بناء الدرج ويرشدون الطلائع في السلامة.",
					image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
					section: "الجوالة",
					activity: "يوم خدمة الربيع",
					date: "2024-05-18",
					location: "محمية عين زحلتا",
					tags: ["درب", "أدوات", "تعليم"],
				},
				{
					id: "castors-hike",
					title: "مستكشفون صغار",
					description: "القنادس ينهون تحدي الخرائط قبل إيصال المياه لفرق العمل.",
					image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
					section: "القنادس",
					activity: "يوم ترميم الدرب",
					date: "2024-05-18",
					location: "محمية عين زحلتا",
					tags: ["فرح", "مساندة", "استكشاف"],
				},
				{
					id: "tool-circle",
					title: "دائرة الأدوات",
					description: "أمين العتاد يشرح قواعد السلامة قبل توزيع المهام.",
					image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1600&q=80",
					section: "الفريق الداعم",
					activity: "يوم ترميم الدرب",
					date: "2024-05-18",
					location: "محمية عين زحلتا",
					tags: ["معدات", "تنظيم", "سلامة"],
				},
			],
		},
	],
	emptyState: {
		title: "لا توجد ألبومات مطابقة الآن",
		description: "جرّبوا تغيير الفلاتر أو الوسوم لاستكشاف المزيد من الأرشيف.",
	},
};

