import type { GalleryPageContent } from "@/lib/translations";

export const galleryPageEn: GalleryPageContent = {
	hero: {
		badge: "Gallery",
		title: "Moments that shaped our scouts",
		description: "Camps under the cedars, service mornings, and badges earned in laughter—curated stories from every section.",
		image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1600&q=80",
		stats: [
			{ value: "8", label: "Albums" },
			{ value: "120+", label: "Photos curated" },
			{ value: "6", label: "Sections represented" },
		],
	},
	filters: {
		sectionLabel: "Sections",
		tagLabel: "Tags",
		sortLabel: "Sort by",
		sortOptions: [
			{ value: "newest", label: "Newest first" },
			{ value: "oldest", label: "Oldest first" },
			{ value: "section", label: "Section A–Z" },
			{ value: "location", label: "Location A–Z" },
		],
	},
	albums: [
		{
			id: "family-welcome-2024",
			title: "Family Welcome Campfire",
			description: "An autumn evening where every section meets new families and raises the first song of the year.",
			coverImage: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
			section: "All sections",
			location: "Parc Saint Jean",
			dateRange: "Sep 14, 2024",
			sortDate: "2024-09-14",
			tags: ["campfire", "family", "tradition"],
			stats: [
				{ value: "18", label: "Frames" },
				{ value: "6", label: "Sections present" },
			],
			images: [
				{
					id: "campfire-welcome",
					title: "First fire circle",
					description: "Louveteaux lead the opening chant as parents gather under the cedars.",
					image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
					section: "Louveteaux",
					activity: "Family Welcome Campfire",
					date: "2024-09-14",
					location: "Parc Saint Jean",
					tags: ["campfire", "song", "parents"],
				},
				{
					id: "castors-lanterns",
					title: "Lantern parade",
					description: "Castors share lanterns they crafted to guide new siblings to the circle.",
					image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
					section: "Castors",
					activity: "Family Welcome Campfire",
					date: "2024-09-14",
					location: "Parc Saint Jean",
					tags: ["crafts", "lantern", "joy"],
				},
				{
					id: "parents-circle",
					title: "Story swap",
					description: "Parents share memories while patrol leaders present their totems.",
					image: "https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?auto=format&fit=crop&w=1600&q=80",
					section: "All sections",
					activity: "Family Welcome Campfire",
					date: "2024-09-14",
					location: "Parc Saint Jean",
					tags: ["community", "story", "welcome"],
				},
			],
		},
		{
			id: "skills-camp-2024",
			title: "Autumn Skills Camp",
			description: "A weekend in the Cedars Plateau focused on pioneering, cooking, and night vigilance.",
			coverImage: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80",
			section: "Scouts & Pionniers",
			location: "Cedars Plateau",
			dateRange: "Oct 4–6, 2024",
			sortDate: "2024-10-04",
			tags: ["camp", "pioneering", "badge work"],
			stats: [
				{ value: "24", label: "Frames" },
				{ value: "3", label: "Patrol competitions" },
			],
			images: [
				{
					id: "skills-camp-flag",
					title: "Flag raising at dawn",
					description: "Scouts secure the mast they built overnight before morning prayer.",
					image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80",
					section: "Scouts",
					activity: "Autumn Skills Camp",
					date: "2024-10-05",
					location: "Cedars Plateau",
					tags: ["flag", "pioneering", "dawn"],
				},
				{
					id: "pioneers-vigil",
					title: "Night watch",
					description: "Pionniers keep vigil beside the chapel before their promise ceremony.",
					image: "https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?auto=format&fit=crop&w=1600&q=80",
					section: "Pionniers",
					activity: "Autumn Skills Camp",
					date: "2024-10-05",
					location: "Cedars Plateau",
					tags: ["promise", "night", "tradition"],
				},
				{
					id: "campfire-chefs",
					title: "Patrol kitchen",
					description: "Teams race to present the best cedar-plank dinner over embers.",
					image: "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1600&q=80",
					section: "Scouts",
					activity: "Autumn Skills Camp",
					date: "2024-10-05",
					location: "Cedars Plateau",
					tags: ["cooking", "competition", "fire"],
				},
			],
		},
		{
			id: "pilgrimage-2024",
			title: "Easter Pilgrimage Weekend",
			description: "Guides and Caravelles hike the Qadisha trail with journals, prayer, and service.",
			coverImage: "https://images.unsplash.com/photo-1521335629791-ce4aec67dd47?auto=format&fit=crop&w=1600&q=80",
			section: "Guides & Caravelles",
			location: "Qadisha Trail",
			dateRange: "Apr 5–7, 2024",
			sortDate: "2024-04-05",
			tags: ["hike", "faith", "sisterhood"],
			stats: [
				{ value: "12", label: "Rosaries prayed" },
				{ value: "9km", label: "Trail distance" },
			],
			images: [
				{
					id: "guides-pilgrimage",
					title: "Pilgrimage pause",
					description: "Guides journal reflections overlooking the valley after their Lenten hike.",
					image: "https://images.unsplash.com/photo-1521335629791-ce4aec67dd47?auto=format&fit=crop&w=1600&q=80",
					section: "Guides",
					activity: "Easter Pilgrimage",
					date: "2024-04-07",
					location: "Qadisha Trail",
					tags: ["journal", "hike", "faith"],
				},
				{
					id: "caravelles-sharing",
					title: "Letters to new friends",
					description: "Caravelles write prayers for the Marseille exchange while resting at the lookout.",
					image: "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1600&q=80",
					section: "Caravelles",
					activity: "Easter Pilgrimage",
					date: "2024-04-06",
					location: "Qadisha Trail",
					tags: ["journaling", "exchange", "sunset"],
				},
				{
					id: "pilgrimage-altar",
					title: "Trail altar",
					description: "A simple altar built with cedar branches for the evening liturgy.",
					image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
					section: "Guides",
					activity: "Easter Pilgrimage",
					date: "2024-04-06",
					location: "Hermitage bend",
					tags: ["altar", "service", "light"],
				},
			],
		},
		{
			id: "service-trail-2024",
			title: "Trail Restoration Day",
			description: "Routiers mentor younger patrols while rebuilding a storm-damaged staircase.",
			coverImage: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
			section: "Routiers",
			location: "Ain Zhalta Reserve",
			dateRange: "May 18, 2024",
			sortDate: "2024-05-18",
			tags: ["service", "trail", "mentorship"],
			stats: [
				{ value: "6", label: "Patrols involved" },
				{ value: "180", label: "Steps repaired" },
			],
			images: [
				{
					id: "routiers-service",
					title: "Restoring a mountain trail",
					description: "Routiers rebuild steps after a storm, mentoring younger patrols.",
					image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
					section: "Routiers",
					activity: "Spring Service Day",
					date: "2024-05-18",
					location: "Ain Zhalta Reserve",
					tags: ["service", "mentorship", "trail"],
				},
				{
					id: "castors-hike",
					title: "Tiny explorers",
					description: "Castors celebrate finishing their first map-and-trail challenge before delivering water.",
					image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
					section: "Castors",
					activity: "Trail Restoration Day",
					date: "2024-05-18",
					location: "Ain Zhalta Reserve",
					tags: ["patrol buddy", "helpers", "joy"],
				},
				{
					id: "tool-circle",
					title: "Tool circle",
					description: "Quartermasters brief everyone on safety and assign tool teams.",
					image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1600&q=80",
					section: "Support team",
					activity: "Trail Restoration Day",
					date: "2024-05-18",
					location: "Ain Zhalta Reserve",
					tags: ["equipment", "briefing", "support"],
				},
			],
		},
	],
	emptyState: {
		title: "No albums match… yet",
		description: "Adjust filters or tags to explore more from our archives.",
	},
};

